apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: level
spec:
  type: LoadBalancer
  ports:
  - port: 6379
  selector:
    app: level
    tier: redis
---
apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: level
spec:
  selector:
    matchLabels:
      app: level
      tier: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: level
        tier: redis
    spec:
      containers:
      - image: redis:5.0.4
        name: redis
        command:
          - redis-server
          - "/redis-master/redis.conf"
        livenessProbe:
          tcpSocket:
            port: 6379
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: example-redis-config
            items:
            - key: redis-config
              path: redis.conf
# apiVersion: v1
# kind: Pod
# metadata:
#   name: redis
# spec:
#   containers:
#   - name: redis
#     image: redis:5.0.4
#     command:
#       - redis-server
#       - "/redis-master/redis.conf"
#     env:
#     - name: MASTER
#       value: "true"
#     ports:
#     - containerPort: 6379
#     resources:
#       limits:
#         cpu: "0.1"
#     volumeMounts:
#     - mountPath: /redis-master-data
#       name: data
#     - mountPath: /redis-master
#       name: config
#   volumes:
#     - name: data
#       emptyDir: {}
#     - name: config
#       configMap:
#         name: example-redis-config
#         items:
#         - key: redis-config
#           path: redis.conf